// Autogenerated code from test/service.proto on Sat, July 09 2016.  DO NOT EDIT!
// {"swiftpath"=>"./SwiftPornExample/SwiftPornExample", "realm"=>true, "objectmapper"=>true}

import Foundation
import RealmSwift
import ObjectMapper

class PostTestRequest: Object, Mappable {

  func mapping(map: Map) {
  }


  required convenience init?(_ map: Map) {
    self.init()
  }

}

class PostTestResponse: Object, Mappable {
  dynamic var origin: String?
  dynamic var url: String?
  dynamic var headers: PostTestResponseHeaders?

  func mapping(map: Map) {
      origin <- map["origin"]
      url <- map["url"]
      headers <- map["headers"]
  }


  required convenience init?(_ map: Map) {
    self.init()
  }

}

class PostTestResponseHeaders: Object, Mappable {
  dynamic var Host: String?

  func mapping(map: Map) {
      Host <- map["Host"]
  }


  required convenience init?(_ map: Map) {
    self.init()
  }

}

