// Autogenerated code from test/service.proto on Sat, July 09 2016.  DO NOT EDIT!
// {"swiftpath"=>"./SwiftPornExample/SwiftPornExample"}

import Foundation
import ObjectMapper

protocol DateTimeTest {
  func post(request: PostTestRequest, completionHandler: ((PostTestResponse? -> Void)?))
}

extension DateTimeTest {
  func post(request: PostTestRequest, completionHandler: ((PostTestResponse? -> Void)?) = nil) {
    let defaultSession = NSURLSession(configuration: NSURLSessionConfiguration.defaultSessionConfiguration())
    let url = NSURL(string: "https://httpbin.org/post")!
    let httpRequest = NSMutableURLRequest(URL: url)
    httpRequest.HTTPMethod = "POST"
    let jsonString = Mapper().toJSONString(request, prettyPrint: true)
    httpRequest.HTTPBody = jsonString?.dataUsingEncoding(NSUTF8StringEncoding)
    let dataTask = defaultSession.dataTaskWithRequest(httpRequest) {
      data, response, error in
        // Handle response
        let postTestResponse = Mapper<PostTestResponse>().map(data?.utf8String())
        completionHandler?(postTestResponse)
      }
    dataTask.resume()
  }

}