// Autogenerated code from test/service.proto on Sat, July 09 2016.  DO NOT EDIT!
// {"swiftpath"=>"./SwiftPornExample/SwiftPornExample", "realm"=>true, "objectmapper"=>true}

import Foundation
import RealmSwift
import ObjectMapper

class DateTimeRequest: Object, Mappable {

  func mapping(map: Map) {
  }


  required convenience init?(_ map: Map) {
    self.init()
  }

}

class DateTimeResponse: Object, Mappable {
  dynamic var time: String?
  // Int objects must be wrapped in a RealmOptional
  var millisecondsSinceEpoch = RealmOptional<Int>()
  dynamic var date: String?

  func mapping(map: Map) {
      time <- map["time"]
      millisecondsSinceEpoch.value <- map["milliseconds_since_epoch"]
      date <- map["date"]
  }


  required convenience init?(_ map: Map) {
    self.init()
  }

}

