// Autogenerated code from test/test.proto on Mon, July 04 2016.  DO NOT EDIT!

import Foundation
import ObjectMapper

class Person: {
  var name: String?
  var id: Int?
  var email: String?
  var phones: [PhoneNumber]?

  enum PhoneType: String {
    case Mobile = "MOBILE"
    case Home = "HOME"
    case Work = "WORK"
  }


  func mapping(map: Map) {
    name <- map["name"]
    id <- map["id"]
    email <- map["email"]
    phones <- map["phones"]
  }


  required convenience init?(_ map: Map) {
    self.init()
  }

}

class AddressBook: {
  var people: [Person]?

  func mapping(map: Map) {
    people <- map["people"]
  }


  required convenience init?(_ map: Map) {
    self.init()
  }

}

